config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users
  get 'user/calendar' => 'users#calendar'
  resources :groups do
    get "join" =>"groups#join"
  end
  get "music/groups" => "musics#groups"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :groups
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image

  has_many :group_users
  has_many :users, through: :group_users,dependent: :destroy
  belongs_to :category

  validates :start_time, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :group_users   #中間テーブル！
  has_many :groups, through: :group_users,dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # 友達フォロー
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  #友達判定
  def matchers
    followings & followers
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController


  def index
    @user = current_user
    @groups = Group.all
    @category = Category.all
  end

  def show
    # @list = List.new
    @group = Group.find(params[:id])
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end


  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user  #current_userを追加@
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)

      redirect_to groups_path
    else
      render 'edit'
    end
  end

 
  def destroy                          # 退会機能
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
      redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :start_time, :user_id, :category_id)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
    def groups
        @groups = Group.where(category_id: Category.find_by(name: "音楽").id)
    end
    
    def new
        @music = Music.new
    end
    
    def create
        @music = Music.new(music_params)
        @music.category_id = Category.find_by(name: "音楽").id
        if @music.save
            redirect_to groups_path
        else
            render :new
        end
    end
    
    private
    def music_params
        params.require(:music).permit(:artist)
    end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.following_relationships.create(create_params)
    redirect_to user_path(params[:following_id])
  end

  def destroy
    @user=current_user
    @relationship =  Relationship.where(following_id: params[:id],follower_id:@user.id)
    @relationship.destroy_all
    redirect_to user_path(params[:id])
  end

  private

  def create_params
    params.permit(:following_id)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @group = current_user.groups
  end

  def calendar
    # @user = User.find(params[:id])
    @user = current_user
    @users = User.all
    @group = current_user.groups
  end


  def show
    @user = User.find(params[:id])
    @relationship = Relationship.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = '名前を入力してください。'
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image, :gender, :age, :prefecture)
  end

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :カテゴリ %>
    <%= f.collection_select :category_id, Category.all, :id, :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.attachment_field :image, class: "form-control-file" %>
  </div>
  <div class="form-group">
    <%= f.label :日時, class: "time_date my-3" %>
    <%= f.datetime_select :start_time %></br>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0 my-5'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー情報</h2>
        <table class="table">
    	     <%= render 'users/user_info', user: @user %> 
        </table>

        <% @category.each do |category| %>
          <div>
            <!--それぞれの作りたいカテゴリーでのコミュニティ一覧ページへのパスを記入お願いします-->
            <% if(category.name == "音楽") %>
              <%= link_to "音楽", music_groups_path %>
            <% elsif(category.name == "グルメ") %>
              <%= link_to "グルメ", root_path %>
            <% elsif(category.name == "お酒") %>
              <%= link_to "お酒", root_path %>
            <% else %>
              <%= link_to "自動車", root_path %>
            <% end %>
          </div>
        <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group List</h2>
        <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <div>
              <%=link_to "コミュニティを作成する",new_group_path %>  <%#=link_to "グループ一覧",groups_path %>
            </div>

            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>日付</th>
            <th colspan="4"></th>
            <th>カテゴリ</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= attachment_image_tag group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.start_time.strftime("%Y年%m月%d日") %></td>
              <% if Category.find(group.category_id).name.present? %>
                <td><%= Category.find(group.category_id).name %></td>
              <% else %>
                <td><p>なし</p></td>
              <% end%>
              <td><i class="fas fa-users"></i><%= group.users.count %></td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>  <!--(br:19)-->
    </div>  <!--(col-md-8 offset-md-1)-->
  </div>
</div> <!--container-->

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%#= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2> <!--何か入れてもいいかも-->
      <%#= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>コミュニティ詳細</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th>日時</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= attachment_image_tag @group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></td>
              <td><%= @group.name %></td>
              <td><%= @group.introduction %></td>
              <td>
                  <% @group.users.each do |member| %>
                  <%= member.name %><br>
                <% end %>
              </td>
              <td><%= @group.start_time.strftime("%Y年%m月%d日 %H:%M") %></td>
              <td>
                 <% if @group.owner_id == current_user.id %>
                   <%= link_to '編集', edit_group_path(@group), class: "btn btn-sm btn-success" %>
                 <% elsif @group.users.include?(current_user) %>
                   <%= link_to 'コミュニティを退会', group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
                 <% else %>
                   <%= link_to 'コミュニティに参加', group_join_path(@group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
           </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/musics/groups.html.erb
<h1>music#groupsページ</h1>
<% if @groups.present? %>
  <h2>Group List</h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <div>
            <%=link_to "グループを作成する",new_group_path %>  <%#=link_to "グループ一覧",groups_path %>
          </div>

          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= attachment_image_tag group, :image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
            <td><%= link_to group.name, group_path(group) %></td>
            <td><%= group.introduction %></td>
            <td><i class="fas fa-users"></i><%= group.users.count %></td>
            <td>
              <% if group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
   <p>音楽カテゴリの投稿はまだありません</p>
  <% end %>