config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users
  get 'user/calendar' => 'users#calendar'
  resources :groups do
    get "join" =>"groups#join"
  end
  get "music/groups" => "musics#groups"


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :group_users   #中間テーブル！
  has_many :groups, through: :group_users,dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # 友達フォロー
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  #友達判定
  def matchers
    followings & followers
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @group = current_user.groups
  end

  def calendar
    # @user = User.find(params[:id])
    @user = current_user
    @users = User.all
    @group = current_user.groups
  end


  def show
    @user = User.find(params[:id])
    @relationship = Relationship.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = '名前を入力してください。'
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image, :gender, :age, :prefecture)
  end

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :start_time)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<tr><%= attachment_image_tag user, :profile_image, size:"100x100", format:'jpeg', fallback:"no_image.jpg" %></tr>
          <tr>
            <th>name</th>
        	<th><%= user.name %></th>
          </tr>
          <tr>
        	<th>introduction</th>
        	<th><%= user.introduction %></th>

app/views/users/calendar.html.erb
<div class='col-md-8 offset-md-1'>
      <h2>カレンダー</h2>
        <div>
         <%=link_to "グループを作成する",new_group_path %>  <%#=link_to "グループ一覧",groups_path %>
        </div>
        <%= month_calendar events: @group do |date, groups| %>
          <%= date.day %>
            <% groups.each do |group| %>
              <%= link_to group.name, group_path(group) %>
          <% end %>
        <% end %>
    </div>  <!--(col-md-8 offset-md-1)-->

app/views/users/edit.html.erb
<<<<<<< HEAD
 users#edit
=======
<div class='container my-5'>
  <div class="row">
    <div class="col-12">
      <h2 class="row offset-lg-5 offset-2 my-5">マイページ編集</h2>
        <%= form_with model:@user, url:user_path, local:true do |f| %>
            <div class="row form-group col-lg-8 col-12 offset-lg-3">
              <%= f.label :画像, class: "col-lg-2 col-12" %>
              <%= f.attachment_field :profile_image %>
            </div>
            <div class="row form-group col-lg-8 col-12 offset-lg-3">
              <%= f.label :名前, class: "col-lg-2 col-12" %>
              <%= f.text_field :name, placeholder:"名前", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="row form-group col-lg-8 col-12 offset-lg-3">
              <%= f.label :性, class: "col-lg-2 col-12" %>
              <%= f.text_field :gender, placeholder:"性別", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="row form-group col-lg-8 col-12 offset-lg-3">
              <%= f.label :年齢, class: "col-lg-2 col-12" %>
              <%= f.text_field :age, placeholder:"○○歳", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="row form-group col-lg-8 col-12 offset-lg-3">
              <%= f.label :出身地, class: "col-lg-2 col-12" %>
              <%= f.text_field :prefecture, placeholder:"○○県", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="row form-group col-lg-8 col-12 offset-lg-3">
              <%= f.label :自己紹介文, class: "col-lg-2 col-12" %>
              <%= f.text_field :introduction, placeholder:"自己紹介文", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="form-group">
              <%= f.submit "登録", class: 'user-botn btn btn-outline-secondary col-lg-2 col-6 offset-lg-5 offset-3' %>
            </div>
        <% end %>
    </div>
  </div>
</div>
>>>>>>> origin/develop

app/views/users/index.html.erb
<div class='container px-5 px-sm-0 my-5'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー一覧</h2>
        <table class="table">
          <tr><%= attachment_image_tag @user, :profile_image, size:"100x100", format:'jpeg', fallback:"no_image.jpg" %></tr>
          <tr>
            <th>name</th>
        	<th><%= @user.name %></th>
          </tr>
          <tr>
        	<th>introduction</th>
        	<th><%= @user.introduction %></th>
    	  </tr>
        </table>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>カレンダー</h2>
        <div>
         <%=link_to "グループを作成する",new_group_path %>
        </div>
        <%= month_calendar events: @group do |date, groups| %> <!--カレンダー表示-->
          <%= date.day %>
            <% groups.each do |group| %>
              <%= link_to group.name, group_path(group) %>
          <% end %>
        <% end %>
    </div>  <!--(col-md-8 offset-md-1)-->
  </div>
</div> <!--container-->

app/views/users/show.html.erb
<div class='container px-5 px-sm-0 my-5'>
  <div class='row'>
    <%# if user_signed_in? && current_user  %>
      <%#=link_to "カレンダー",user_calendar_path %>
    <%# end %>
    <div class="col-lg-2 col-12 mt-4 offset-lg-2">
            <%= attachment_image_tag @user, :profile_image, format:'jpeg', fallback:"no_image.jpg", class:"img-fluid" %>
          </div>
          <div class="col-lg-5 col-12 offset-lg-1 mt-4 mr-auto">
            <table class="table">
              <tr>
                <th>名前</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>性</th>
                <th><%= @user.gender %></th>
              </tr>
              <tr>
                <th>年齢</th>
                <th><%= @user.age %></th>
              </tr>
              <tr>
                <th>出身地</th>
                <th><%= @user.prefecture %></th>
              </tr>
              <tr>
                <th>自己紹介</th>
                <th><%= @user.introduction %></th>
              </tr>
            </table>


            <div class="link-edit row">
              <%= link_to '編集', edit_user_path(@user.id), class:"col-12 btn btn_success" %>
            </div>
          </div>
    </div>
  </div>
</div